/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.parabitinss;

import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arvin
 */
public class DetailedTable extends javax.swing.JDialog implements Runnable{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailedTable.class.getName());
    ParabitDBC db1; 
    public DetailedTable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setVisible(false);
        db1=new ParabitDBC();
        tableLoader();
    }

    private void tableLoader(){
        Thread ob= new Thread(this);
        ob.start();
    }
    
    @Override
    public void run(){  
       LocalDate lastDate=null;   
       while(true){
       try{
                int load,rload,TollCap=0;
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                LocalDate curDate=LocalDate.now();
                String sql1 = "SELECT NoOfGates from CheckPointToll where CpNo=2;";
                db1.rs = db1.stm.executeQuery(sql1);
                if(db1.rs.next()){
                   TollCap = (db1.rs.getInt("NoOfGates")/2)* 60;
                }
                String  sql2 = "SELECT Time, SUM(APCount) AS APCount, SUM(ACCount) AS ACCount, SUM(RPCount) AS RPCount, SUM(RCCount) AS RCCount," +
                    "SUM(APCount + ACCount) AS TotalCount,SUM(RPCount + RCCount) AS RTotal " +
                    "FROM tollpassedveh " +
                    "WHERE TollCpNo = 2 AND Date = CURRENT_DATE " +
                    "GROUP BY Time " +
                    "ORDER BY CAST(Time AS UNSIGNED);";
                 db1.rs = db1.stm.executeQuery(sql2);
                
                if (!curDate.equals(lastDate)) {
                    int col = model.getColumnCount();
                    int hourIndex = 1;
                    load = 0;
                    rload = 0;

                    while (db1.rs.next() && hourIndex < col) {
                        int apCount = db1.rs.getInt("APCount");
                        int acCount = db1.rs.getInt("ACCount");
                        int rpCount = db1.rs.getInt("RPCount");
                        int rcCount = db1.rs.getInt("RCCount");
                        int totalCount = db1.rs.getInt("TotalCount");
                        int rtotal = db1.rs.getInt("RTotal");

                        // Entry data
                        model.setValueAt(apCount, 1, hourIndex);
                        model.setValueAt(acCount, 2, hourIndex);
                        model.setValueAt(totalCount, 3, hourIndex);
                        model.setValueAt(load, 4, hourIndex);
                        load += (TollCap - totalCount);

                        // Return data
                        model.setValueAt(rpCount, 7, hourIndex);
                        model.setValueAt(rcCount, 8, hourIndex);
                        model.setValueAt(rtotal, 9, hourIndex);
                        model.setValueAt(rload, 10, hourIndex);
                        rload += (TollCap - rtotal);

                        hourIndex++;
                    }

                    lastDate = curDate;
                }
                Thread.sleep(1000);    
             }
             catch(Exception e){
               System.out.print(e);
             }
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null, null, null, "  Arrived", "Vehicle", null, null, null, null, null, null, null, null, null, null, null},
                {"Personal", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Commercial", "", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Total Arrived", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Load", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", "", null, null, null, null, null, null, null, null, null, null, "Returned", "Vehicle", null, null, null, null, null, null, null, null, null, null, null},
                {"Personal", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Commercial", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Total Returned", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Load", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DetailedTable dialog = new DetailedTable(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
