/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.parabitinss;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author arvin
 */
public class PbtVhReg extends javax.swing.JDialog {

   ParabitDBC db1;
   String  s1,s2,chk;
   File sImg  = null;
   int result=-2;
   
    public PbtVhReg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(0, 0);
        
        db1 = new ParabitDBC();
        jlNew.setVisible(true);
        b8.setVisible(false);
        
        try {
            
             s1="Select * from state;";
             db1.rs=db1.stm.executeQuery(s1);
             while(db1.rs.next())
              {
                s2 = db1.rs.getInt("StateCode") + "," + db1.rs.getString("StateName") + "," + db1.rs.getString("StateAbbreviation"); 
                
                 cb1.addItem(s2);
                 cb2.addItem(s2);
                 cb3.addItem(s2);
                 cb4.addItem(s2);
                 cb5.addItem(s2);
                 cb6.addItem(s2);
             }
             
             s1="Select VecType from personalvehtype;";
             db1.rs=db1.stm.executeQuery(s1);
             while(db1.rs.next())
              {
                s2 = db1.rs.getString("VecType"); 
                cb7.addItem(s2);
                cb9.addItem(s2);
                cb11.addItem(s2);
             }
             
             s1="Select FType from fueltype;";
             db1.rs=db1.stm.executeQuery(s1);
             while(db1.rs.next())
              {
                s2 = db1.rs.getString("FType"); 
                cb8.addItem(s2);
                cb10.addItem(s2);
                cb12.addItem(s2);      
             }
             
         } catch (SQLException ex) {
             Logger.getLogger(PbtEmpLog.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    public PbtVhReg(java.awt.Frame parent, boolean modal, String ls) {
        
        super(parent, modal);
        initComponents();
  
        db1 = new ParabitDBC();
        
        jlNew.setVisible(true);
        tf23.setVisible(false);
        b7.setVisible(false);
        b8.setVisible(true);

        cb1.removeAllItems();
        cb2.removeAllItems();
        cb3.removeAllItems();
        cb4.removeAllItems();
        cb5.removeAllItems();
        cb6.removeAllItems();
        cb7.removeAllItems();
        cb8.removeAllItems();
        cb9.removeAllItems();
        cb10.removeAllItems();
        cb11.removeAllItems();
        cb12.removeAllItems();
         
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
        b6.setVisible(false);
        
        cb1.setEnabled(false);
        cb2.setEnabled(false);
        cb3.setEnabled(false);
        cb4.setEnabled(false);
        cb5.setEnabled(false);
        cb6.setEnabled(false);
        cb7.setEnabled(false);
        cb8.setEnabled(false);
        cb9.setEnabled(false);
        cb10.setEnabled(false);
        cb11.setEnabled(false);
        cb12.setEnabled(false);
        
        chk=ls; 
        vhCheck(ls);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        tf10 = new javax.swing.JTextField();
        tf11 = new javax.swing.JTextField();
        tf12 = new javax.swing.JTextField();
        tf13 = new javax.swing.JTextField();
        tf15 = new javax.swing.JTextField();
        tf17 = new javax.swing.JTextField();
        tf21 = new javax.swing.JTextField();
        tf22 = new javax.swing.JTextField();
        tf23 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        cb7 = new javax.swing.JComboBox<>();
        cb8 = new javax.swing.JComboBox<>();
        b7 = new javax.swing.JButton();
        jlNew = new javax.swing.JLabel();
        cb13 = new javax.swing.JComboBox<>();
        cb14 = new javax.swing.JComboBox<>();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        b8 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        tf49 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tf24 = new javax.swing.JTextField();
        tf25 = new javax.swing.JTextField();
        tf26 = new javax.swing.JTextField();
        tf27 = new javax.swing.JTextField();
        tf28 = new javax.swing.JTextField();
        tf30 = new javax.swing.JTextField();
        tf31 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tf33 = new javax.swing.JTextField();
        tf35 = new javax.swing.JTextField();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox<>();
        cb4 = new javax.swing.JComboBox<>();
        cb9 = new javax.swing.JComboBox<>();
        cb10 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        tf50 = new javax.swing.JTextField();
        tf51 = new javax.swing.JTextField();
        tf52 = new javax.swing.JTextField();
        tf53 = new javax.swing.JTextField();
        tf54 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        tf37 = new javax.swing.JTextField();
        tf38 = new javax.swing.JTextField();
        tf46 = new javax.swing.JTextField();
        tf39 = new javax.swing.JTextField();
        tf40 = new javax.swing.JTextField();
        tf48 = new javax.swing.JTextField();
        tf41 = new javax.swing.JTextField();
        tf43 = new javax.swing.JTextField();
        tf44 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        cb5 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cb6 = new javax.swing.JComboBox<>();
        cb11 = new javax.swing.JComboBox<>();
        cb12 = new javax.swing.JComboBox<>();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        tf55 = new javax.swing.JTextField();
        tf56 = new javax.swing.JTextField();
        tf57 = new javax.swing.JTextField();
        tf58 = new javax.swing.JTextField();
        tf59 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Veh Registr No.");

        jLabel5.setText("Vehicl No.");

        jLabel6.setText("Vehicle Category");

        jLabel7.setText("Vehicle Name");

        jLabel8.setText("RTO Reg No");

        jLabel9.setText("Owner Name");

        jLabel10.setText("Owner Mob");

        jLabel11.setText("Emergency Name");

        jLabel12.setText("Emergency Mob");

        jLabel13.setText("Driver Name");

        jLabel14.setText("Driver Mob");

        jLabel15.setText("Drived By");

        jLabel17.setText("No Of Passenger");

        jLabel18.setText("Fuel Type");

        jLabel19.setText("From City");

        jLabel20.setText("From State");

        jLabel21.setText("To City");

        jLabel22.setText("To State");

        jLabel23.setText("Arrival Date");

        jLabel24.setText("Return Date");

        jLabel25.setText("Other Destinations");

        jLabel26.setText("Vip");

        jLabel27.setText("Vehicle Image");

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });

        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });

        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });

        tf13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf13ActionPerformed(evt);
            }
        });

        tf15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf15ActionPerformed(evt);
            }
        });

        tf17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf17ActionPerformed(evt);
            }
        });

        tf22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf22ActionPerformed(evt);
            }
        });

        b1.setText("Reset");

        b2.setText("Submit");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cb7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cb8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        b7.setText("Choose File");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        cb13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb13ActionPerformed(evt);
            }
        });

        cb14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        b8.setText("Pass");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        jLabel32.setText("For Event");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(79, 79, 79))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(51, 51, 51))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel7))
                                        .addGap(59, 59, 59)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(67, 67, 67))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(63, 63, 63)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6))
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf2)
                            .addComponent(tf4)
                            .addComponent(tf5)
                            .addComponent(tf6)
                            .addComponent(tf7)
                            .addComponent(tf8)
                            .addComponent(tf9)
                            .addComponent(tf10)
                            .addComponent(tf11)
                            .addComponent(tf1)
                            .addComponent(cb7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(b1))
                .addGap(37, 37, 37)
                .addComponent(b8)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(b2)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf15, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf17, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf21, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf22, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb1, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                                    .addComponent(cb2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb8, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf49, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNew, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf23, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel17)
                                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel32)
                                                    .addComponent(tf49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel18)
                                                    .addComponent(cb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel19)
                                            .addComponent(tf15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel7)
                                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tf4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel8)
                                    .addComponent(tf17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel9)
                                    .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel10))
                                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)))
                            .addComponent(tf7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel11))
                                .addComponent(jLabel24))
                            .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel25)
                    .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel26)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1)
                            .addComponent(b2)
                            .addComponent(b8)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlNew, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal Vehicle Registration", jPanel1);

        jLabel16.setText("Owner Name");

        jLabel28.setText("Owner Mob1");

        jLabel29.setText("Owner Mob2");

        jLabel30.setText("Driver Name");

        jLabel31.setText("Vehicle Type");

        jLabel33.setText("Vehicle Capacity");

        jLabel34.setText("Permit Type");

        tf24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf24ActionPerformed(evt);
            }
        });

        tf26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf26ActionPerformed(evt);
            }
        });

        tf31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf31ActionPerformed(evt);
            }
        });

        jLabel38.setText("Fuel Type");

        jLabel39.setText("From City");

        jLabel40.setText("From State");

        jLabel41.setText("To City");

        jLabel42.setText("To State");

        b3.setText("Reset");

        b4.setText("Submit");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Driver Mob");

        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cb9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cb10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jLabel36.setText("Permit Type");

        jLabel52.setText("Permit Validity");

        jLabel53.setText("Authorized For");

        jLabel54.setText("Zone Allowed");

        jLabel55.setText("Trip Count");

        tf50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf50ActionPerformed(evt);
            }
        });

        tf53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf53ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33)
                                .addComponent(jLabel34)
                                .addComponent(jLabel38)
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel40)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel16))
                                .addComponent(jLabel29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf35, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(tf33, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(tf28)
                            .addComponent(tf30)
                            .addComponent(tf31)
                            .addComponent(tf27)
                            .addComponent(tf26, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(tf25, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(cb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(174, 174, 174)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf50)
                            .addComponent(tf51)
                            .addComponent(tf52)
                            .addComponent(tf53, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(tf54)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(b3)
                        .addGap(56, 56, 56)
                        .addComponent(b4)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(tf50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(tf51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(tf52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel54)
                    .addComponent(tf53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(tf54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cb9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tf33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(tf35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42)
                    .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3)
                    .addComponent(b4))
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Commercial Vehicle Registration", jPanel2);

        jLabel43.setText("To City");

        jLabel35.setText("Vehicle Type");

        jLabel37.setText("Vehicle Capacity");

        jLabel44.setText("Permit Type");

        tf37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf37ActionPerformed(evt);
            }
        });

        tf39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf39ActionPerformed(evt);
            }
        });

        tf43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf43ActionPerformed(evt);
            }
        });

        jLabel45.setText("Fuel Type");

        jLabel46.setText("Owner Name");

        jLabel47.setText("From City");

        jLabel48.setText("Owner Mob1");

        jLabel49.setText("From State");

        jLabel50.setText("Owner Mob2");

        jLabel51.setText("Driver Name");

        jLabel1.setText("To State");

        b5.setText("Reset");

        b6.setText("Submit");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        cb5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Driver Mob");

        cb6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });

        cb11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cb12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jLabel56.setText("Permit Type");

        jLabel57.setText("Permit Validity");

        jLabel58.setText("Authorized For");

        jLabel59.setText("Zone Allowed");

        jLabel60.setText("Trip Count");

        tf55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf55ActionPerformed(evt);
            }
        });

        tf58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf58ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel48)
                    .addComponent(jLabel50)
                    .addComponent(jLabel37)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel49))
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb6, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                            .addComponent(tf48, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf46, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb12, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf44, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf43, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb11, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf41, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf40, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf39, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf38, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf37, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel58)
                                    .addComponent(jLabel57)))
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b5)
                        .addGap(48, 48, 48)
                        .addComponent(b6)
                        .addGap(120, 120, 120)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf56, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf57, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf58, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf59, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf55, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(323, 323, 323))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(tf37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56)
                    .addComponent(tf55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(tf38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57)
                    .addComponent(tf56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(tf39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58)
                    .addComponent(tf57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(tf40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(tf58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel60)
                    .addComponent(tf59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cb11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tf43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(tf44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(cb12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(tf46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(cb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(tf48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b5)
                    .addComponent(b6))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HeavyDuty Vehicle Registration", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void vhCheck(String ls){
        try {
                        s1="Select * from personalvehreg where VNo='"+ls+"';";
                        db1.rs=db1.stm.executeQuery(s1);
                         if (db1.rs.next())
                          {
                                 b8.setVisible(true);
                                 tf1.setText(db1.rs.getString("VRegNo"));
                                 tf2.setText(db1.rs.getString("VNo")); 
                                 cb7.addItem(db1.rs.getString("VCategoryFK")); 
                                 tf4.setText(db1.rs.getString("VName"));
                                 tf5.setText(db1.rs.getString("RTORegNo"));
                                 tf6.setText(db1.rs.getString("OwnerName"));
                                 tf7.setText(db1.rs.getString("OwnerMob"));
                                 tf8.setText(db1.rs.getString("EmergencyName"));
                                 tf9.setText(db1.rs.getString("EmergencyMob"));
                                 tf10.setText(db1.rs.getString("DriverName"));
                                 tf11.setText(db1.rs.getString("DriverMob"));
                                 tf12.setText(db1.rs.getString("DrivedBy"));
                                 tf13.setText(db1.rs.getString("NoOfPassenger"));
                                 cb8.addItem(db1.rs.getString("FuelTypeFK"));
                                 tf15.setText(db1.rs.getString("FromCity"));
                                 cb1.addItem(""+db1.rs.getInt("FromStateFK"));
                                 tf17.setText(db1.rs.getString("ToCity"));
                                 cb2.addItem(""+db1.rs.getInt("ToStateFK"));
                              
                                SimpleDateFormat simpleDate = new SimpleDateFormat("dd-MM-yyyy");

                                Date sqlDate1 = db1.rs.getDate(22); 
                                Date sqlDate2 = db1.rs.getDate(23);

                                String arrDate = simpleDate.format(sqlDate1);
                                String retDate = simpleDate.format(sqlDate2);

                                date1.setDate(sqlDate1);
                                date2.setDate(sqlDate2);
                                
                                 
                                 tf21.setText(db1.rs.getString("OtherDest"));
                                 tf22.setText(db1.rs.getString("VIP"));
                                 cb13.addItem(""+db1.rs.getInt("TollIn"));
                                 cb14.addItem(""+db1.rs.getInt("TollOut"));

                                 byte[] imgBytes = db1.rs.getBytes("Vimg");
                                 ImageIcon icon = new ImageIcon(imgBytes);
                                 Image img= icon.getImage();
                                 Image imgScale = img.getScaledInstance(jlNew.getWidth(), jlNew.getHeight(), Image.SCALE_SMOOTH);
                                 ImageIcon scaledImage = new ImageIcon(imgScale);
                                 jlNew.setIcon(scaledImage);
                           }
                     
                               
                            s1="Select * from commercialvehreg where OwnerMob1='"+ls+"' OR OwnerMob2 = '"+ls+"';";
                            db1.rs=db1.stm.executeQuery(s1);
                            if (db1.rs.next()) {
                                
                                  tf24.setText(db1.rs.getString("OwnerName"));
                                  tf25.setText(db1.rs.getString("OwnerMob1"));
                                  tf26.setText(db1.rs.getString("OwnerMob2"));
                                  tf27.setText(db1.rs.getString("DriverName"));
                                  tf28.setText(db1.rs.getString("DriverMobNo"));
                                  cb11.setSelectedItem(db1.rs.getString("VehicleTypeFK"));
                                  tf30.setText(db1.rs.getString("FuelType"));
                                  tf31.setText(db1.rs.getString("VehicleCapacity"));
                                  cb12.setSelectedItem(db1.rs.getString("PermitType"));
                                  tf33.setText(db1.rs.getString("FromCity"));
                                  cb3.setSelectedItem("" + db1.rs.getInt("FromState"));
                                  tf35.setText(db1.rs.getString("ToCity"));
                                  cb4.setSelectedItem("" + db1.rs.getInt("ToState"));
                                  tf25.setText(db1.rs.getString("OwnerMob1"));
                                  tf26.setText(db1.rs.getString("OwnerMob2"));
                                  tf27.setText(db1.rs.getString("DriverName"));
                                  tf28.setText(db1.rs.getString("DriverMobNo"));
                                  cb11.setSelectedItem(db1.rs.getString("VehicleTypeFK"));
                                  tf30.setText(db1.rs.getString("FuelType"));
                                  tf31.setText(db1.rs.getString("VehicleCapacity"));
                                  cb12.setSelectedItem(db1.rs.getString("PermitType"));
                                  tf33.setText(db1.rs.getString("FromCity"));
                                  cb3.setSelectedItem("" + db1.rs.getInt("FromState"));
                                  tf35.setText(db1.rs.getString("ToCity"));
                                  cb4.setSelectedItem("" + db1.rs.getInt("ToState"));
                                  cb13.setSelectedItem("" + db1.rs.getInt("TollIn"));
                                  cb14.setSelectedItem("" + db1.rs.getInt("TollOut"));
                             }
                 
         } catch (SQLException ex) {
             Logger.getLogger(PbtEmpLog.class.getName()).log(Level.SEVERE, null, ex);
         }
         
    }
    
    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf5ActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf6ActionPerformed

    private void tf15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf15ActionPerformed

    private void tf17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf17ActionPerformed

    private void tf22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf22ActionPerformed

    private void tf39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf39ActionPerformed

    private void tf43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf43ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf37ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
       String s, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10,
       s11, s12, s13, s14, s15, s16, s17, s18,
       s21, s22,s23;

        s1 = tf1.getText();
        s2 = tf2.getText();
        s3 = (String) cb7.getSelectedItem(); 
        s4 = tf4.getText();
        s5 = tf5.getText();
        s6 = tf6.getText();
        s7 = tf7.getText();
        s8 = tf8.getText();
        s9 = tf9.getText();
        s10 = tf10.getText();
        s11 = tf11.getText();
        s12 = tf12.getText();
        s13 = tf13.getText();
//        s14 = (String) cb8.getSelectedItem();
        s15 = tf15.getText();
        s16 = (String) cb1.getSelectedItem();
        s17 = tf17.getText();
        s18 = (String) cb2.getSelectedItem();
//        s19 = tf19.getText();
//        s20 = tf20.getText();
        
        s21 = tf21.getText();
        s22 = tf22.getText();
        s23 = tf49.getText();
        
       s = "INSERT INTO personalvehreg(ForEvent, VNo, VCategoryFK,VName,RTORegNo, OwnerName, OwnerMob,EmergencyName,EmergencyMob,"
               + "DriverName,DriverMob,DrivedBy,VIP, FuelTypeFK, FromCity,FromStateFK,ToCity,ToStateFK,ArrivalDate,`ReturnDate`,"
               + "OtherDest,NoOfPassenger,VImg,`TollIn`,`TollOut`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?)";
       
       try {
           
//                FileInputStream fis = new FileInputStream(sImg);

                db1.ps = db1.con.prepareStatement(s);
                
                db1.ps.setString(1, s23);
                db1.ps.setString(2, s2);
                db1.ps.setInt(3, cb7.getSelectedIndex());
                db1.ps.setString(4, s4);
                db1.ps.setString(5, s5);
                db1.ps.setString(6, s6);
                db1.ps.setString(7, s7);
                db1.ps.setString(8, s8);
                db1.ps.setString(9, s9);
                db1.ps.setString(10, s10);
                db1.ps.setString(11, s11);
                db1.ps.setString(12, s12);
                db1.ps.setString(13, s13);
                db1.ps.setInt(14, cb8.getSelectedIndex());
                db1.ps.setString(15, s15);
                db1.ps.setInt(16, cb1.getSelectedIndex());
                db1.ps.setString(17, s17);
                db1.ps.setInt(18, cb2.getSelectedIndex());
                
                
                if (date1 != null && date2 != null) {
                        java.util.Date arrivalDate = date1.getDate();    // JDateChooser
                        java.util.Date  returnDate  = date2.getDate();
                        java.sql.Date sqlRetDate = new java.sql.Date(returnDate.getTime());
                        java.sql.Date sqlArrDate = new java.sql.Date(arrivalDate.getTime());
                        
                        db1.ps.setDate(19, sqlArrDate);
                        db1.ps.setDate(20, sqlRetDate);
                    } else {
                        db1.ps.setNull(19, java.sql.Types.DATE); 
                        db1.ps.setNull(20, java.sql.Types.DATE);
                    }
                
                db1.ps.setString(21, s21);
                db1.ps.setString(22, s22);
                db1.ps.setInt(24, cb13.getSelectedIndex());
                db1.ps.setInt(25, cb14.getSelectedIndex());
                
                if(result==0){
                    FileInputStream fis = new FileInputStream(sImg);
                    db1.ps.setBinaryStream(23, fis, (int) sImg.length());
                    db1.ps.executeUpdate();
                    
                    String regNo="";
                    String fState,state,regno;
                    int sno=0,i=0;
                    int stateCode = cb1.getSelectedIndex();       
                    db1.rs=db1.stm.executeQuery("Select StateAbbreviation from state where StateCode='"+stateCode+"';");
                    if(db1.rs.next()){
                       fState=  db1.rs.getString(1);
   //                    state= ""+fState.charAt(0)+fState.charAt(1);
                       state= ""+fState;
                       db1.rs=db1.stm.executeQuery("Select SNo,ArrivalDate from personalvehreg where VNo='"+s2+"';");
                       if(db1.rs.next()){
                           java.sql.Date sqlArrDate = db1.rs.getDate("ArrivalDate");
                           SimpleDateFormat simpleDate = new SimpleDateFormat("dd-MM-yyyy");
                           String arrDate= simpleDate.format(sqlArrDate);
                           String date= ""+arrDate.charAt(0)+ arrDate.charAt(1);
                           sno=db1.rs.getInt("SNo");
                           regNo=state+date+sno;
                           System.out.println(sno + "    "+regNo);
                            i = db1.stm.executeUpdate("Update personalvehreg SET VRegNo='"+regNo+"' WHERE VNo='"+s2+"';");
                        }
                      }
                    if(i!=0){
                    System.out.println("Successfully Submited");
                    JOptionPane.showMessageDialog(this,"Successfully Submited");
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"VehRegNo is Not Given");
                    }
                }
                else{
                     JOptionPane.showMessageDialog(this,"Pleease Select Valid Image");
                }
                
                 QrCode qr=new QrCode( s2);
                
         } catch (SQLException ex) {
             Logger.getLogger(PbtEmpLog.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this,"Not Submitted Please fill necessary Details");
         } catch (FileNotFoundException ex) {
           Logger.getLogger(PbtVhReg.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_b2ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        String s,s37, s38, s39, s40, s41, s42, s43, s44, s45, s46, s47, s48, s49;

        s37 = tf37.getText();
        s38 = tf38.getText();
        s39 = tf39.getText();
        s40 = tf40.getText();
        s41 = tf41.getText(); 
        
        s43 = (String) cb12.getSelectedItem();
        s44 = tf43.getText();
        s45 = tf44.getText();
        s46 = tf46.getText();
       
        s48 = tf48.getText();
        
        s = "INSERT INTO commercialvehreg (OwnerName, OwnerMob1, OwnerMob2, DriverName, DriverMobNo, VehicleTypeFK, FuelType, VehicleCapacity, PermitType,Fromcity, FromState, ToCity, ToState) VALUES ('" + s37 + "','" + s38 + "','" + s39 + "','" + s40 + "','" + s41 + "','" + cb11.getSelectedIndex() + "','" + s43+ "','" + s44 + "','" + s45 + "','" + s46 + "','" + cb5.getSelectedIndex() + "','" + s48 + "','" + cb6.getSelectedIndex()+ "');";
       try {
             db1.stm.executeUpdate(s);
             System.out.println("Submitted successfully");
             JOptionPane.showMessageDialog(this,"Successfully Submited");
         } catch (SQLException ex) {
             Logger.getLogger(PbtEmpLog.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_b6ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        String s,s24, s25, s26, s27, s28, s29, s30, s31, s32, s33, s34, s35, s36;
        s24 = tf24.getText();
        s25 = tf25.getText();
        s26 = tf26.getText();
        s27 = tf27.getText();
        s28 = tf28.getText();
        
        s30 = (String) cb10.getSelectedItem();
        s31 = tf31.getText();
        s32 = tf33.getText();
        s33 = tf33.getText();
      
        s35 = tf35.getText();


        s = "INSERT INTO commercialvehreg(OwnerName, OwnerMob1, OwnerMob2, DriverName, DriverMobNo, VehicleTypeFK, FuelType, VehicleCapacity, PermitType,Fromcity, FromState, ToCity, ToState) VALUES ('" + s24 + "','" + s25 + "','" + s26 + "','" + s27 + "','" + s28 + "','" + cb9.getSelectedIndex() + "','" + s30 + "','" + s31 + "','" + s32 + "','" + s33 + "','" + cb3.getSelectedIndex() + "','" + s35 + "','" + cb4.getSelectedIndex()  + "');";
        try {
            db1.stm.executeUpdate(s);
            System.out.println("Submitted successfully");
            JOptionPane.showMessageDialog(this,"Successfully Submited");
         } catch (SQLException ex) {
             Logger.getLogger(PbtEmpLog.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_b4ActionPerformed

    private void tf26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf26ActionPerformed

    private void tf24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf24ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed

    }//GEN-LAST:event_cb5ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
  
    }//GEN-LAST:event_cb6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        JFileChooser img = new JFileChooser();
        result = img.showOpenDialog(this);   //result tells you what the user did (approved, canceled, or error) stores 0,1,-1
//        File sImg  = null;
        
        if(result == img.APPROVE_OPTION){
            sImg = img.getSelectedFile();    // It stores path, name, and metadata of the chosen file – not the file's content.
            tf23.setText(sImg.getName());
            try {
                // Read image using ImageIO
                BufferedImage bufferedImage = ImageIO.read(sImg);

                // Scale image to fit the JLabel
                Image imgScale = bufferedImage.getScaledInstance(jlNew.getWidth(), jlNew.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledImage = new ImageIcon(imgScale);
                // Set scaled image icon to JLabel
                jlNew.setIcon(scaledImage);
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Failed to load image: " + ex.getMessage());
            }
}
    }//GEN-LAST:event_b7ActionPerformed

    private void tf13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf13ActionPerformed

    private void tf31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf31ActionPerformed

    private void cb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb13ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        if(cb1.getSelectedIndex()==23){
          String  s1="MP";
          String  s="Select * From CheckPointToll where CPName LIKE '%"+s1+"%';";
            try {
                db1.rs=db1.stm.executeQuery(s);
                System.out.println("Fetched Succesfully");
                while(db1.rs.next()){
                    cb13.addItem((String) db1.rs.getString("CPName"));
                     cb14.addItem((String) db1.rs.getString("CPName"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(PbtVhReg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        LocalDate currDate=LocalDate.now();
        LocalTime curTime = LocalTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        String sqlTime = curTime.format(formatter);  
        try{
                s2="Select * from personalvehreg where Vno='"+chk+"';";
                db1.rs=db1.stm.executeQuery(s2);
                if(db1.rs.next()){
                     if(db1.rs.getInt("Status")==1){
                        s1="Update personalvehreg set Status=0,ChkOutTime='"+ sqlTime+"' where VNo='"+chk+"';";
                         db1.stm.executeUpdate(s1);
                         String s="UPDATE tollpassedveh SET RPCOUNT=APCOUNT+1,RCCOUNT=APCOUNT+1 WHERE Date=CURRENT_DATE and HOUR('"+sqlTime+"')=Cast(Time As UNSIGNED) AND TollCpNo=2";
                         db1.stm.executeUpdate(s);
                         JOptionPane.showMessageDialog(this,"Returned");
                     }
                     else if(db1.rs.getInt("Status")==-1){
                         s1="Update personalvehreg set Status=1,ChkInTime='"+ sqlTime+"' where VNo='"+chk+"';";
                        db1.stm.executeUpdate(s1);
                        String s="UPDATE tollpassedveh SET APCount=APCount+1,ACCount=ACCount+1 WHERE Date=CURRENT_DATE AND HOUR('"+sqlTime+"')=Cast(Time AS UNSIGNED) AND TollCpNo=2";
                        db1.stm.executeUpdate(s);
                        JOptionPane.showMessageDialog(this,"Arrived");     
                    }
                     else if(db1.rs.getInt("Status")==0){
                        JOptionPane.showMessageDialog(this,"Vehicle Not verified");     
                    } 
                    else{
                        JOptionPane.showMessageDialog(this,"Vehicle Not verified");     
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Vehicle Not Registered");     
                }
                b8.setEnabled(false);
          }catch(Exception e){
            System.out.println(e);  
          }
        this.dispose();
    }//GEN-LAST:event_b8ActionPerformed

    private void tf50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf50ActionPerformed

    private void tf53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf53ActionPerformed

    private void tf55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf55ActionPerformed

    private void tf58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf58ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       LocalDate currDate=LocalDate.now();
       String s1="Update personalvehreg set Status=1,NoOfPassenger='"+tf13.getText()+"',ForEvent='"+tf49+"',ArrivalDate='"+currDate+"' where VNo='"+chk+"';";
       try {
           db1.stm.executeUpdate(s1);
       } catch (SQLException ex) {
           System.getLogger(PbtVhReg.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
       }
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtVhReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtVhReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtVhReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtVhReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PbtVhReg dialog = new PbtVhReg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb10;
    private javax.swing.JComboBox<String> cb11;
    private javax.swing.JComboBox<String> cb12;
    private javax.swing.JComboBox<String> cb13;
    private javax.swing.JComboBox<String> cb14;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JComboBox<String> cb4;
    private javax.swing.JComboBox<String> cb5;
    private javax.swing.JComboBox<String> cb6;
    private javax.swing.JComboBox<String> cb7;
    private javax.swing.JComboBox<String> cb8;
    private javax.swing.JComboBox<String> cb9;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlNew;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf11;
    private javax.swing.JTextField tf12;
    private javax.swing.JTextField tf13;
    private javax.swing.JTextField tf15;
    private javax.swing.JTextField tf17;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf21;
    private javax.swing.JTextField tf22;
    private javax.swing.JTextField tf23;
    private javax.swing.JTextField tf24;
    private javax.swing.JTextField tf25;
    private javax.swing.JTextField tf26;
    private javax.swing.JTextField tf27;
    private javax.swing.JTextField tf28;
    private javax.swing.JTextField tf30;
    private javax.swing.JTextField tf31;
    private javax.swing.JTextField tf33;
    private javax.swing.JTextField tf35;
    private javax.swing.JTextField tf37;
    private javax.swing.JTextField tf38;
    private javax.swing.JTextField tf39;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf40;
    private javax.swing.JTextField tf41;
    private javax.swing.JTextField tf43;
    private javax.swing.JTextField tf44;
    private javax.swing.JTextField tf46;
    private javax.swing.JTextField tf48;
    private javax.swing.JTextField tf49;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf50;
    private javax.swing.JTextField tf51;
    private javax.swing.JTextField tf52;
    private javax.swing.JTextField tf53;
    private javax.swing.JTextField tf54;
    private javax.swing.JTextField tf55;
    private javax.swing.JTextField tf56;
    private javax.swing.JTextField tf57;
    private javax.swing.JTextField tf58;
    private javax.swing.JTextField tf59;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables

}
